### ISSUE TITLE
Decide on a target sampling rate

### ISSUE THREAD

**Issue by mikelg128** [space-city-rocketry/Avionics#18]

**Comment by samarm96** [comment]
This is sort of done. I've set the sampling rate to the fastest it can be (250 ms), but haven't done anything fancy to have diff sampling rates for each sensor

**Comment by samarm96** [comment]
The more I think about this, the harder I feel like it'll be to have separate sampling rates for each sensor. We'd be better off just optimizing the current timing function

**Comment by mikelg128** [comment]
This will need to be reassessed with the implementation of the Teensy 3.5
